name: howdy
description: A new Flutter project.

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.10
  convert: ^3.0.1
  cupertino_icons: ^1.0.2
  either_dart: ^0.1.4
  equatable: ^2.0.3
  file_picker: ^4.5.1
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  firebase_storage: ^10.2.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  fluttericon: ^2.0.0
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^9.2.0
  google_sign_in: ^5.2.4
  http: ^0.13.4
  intl: ^0.17.0
  intl_phone_field: ^3.0.1
  rsa_encrypt: ^2.0.0
  shared_preferences: ^2.0.13
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.1.2+1

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png

flutter_icons:
  image_path: "assets/logo.png"
  android: true
  ios: true

flutter:
  assets:
    - assets/imgs/
  
  
  
  uses-material-design: true
  
  